// modules/web/src/views/login/Login.jsx
import React, { useMemo, useState, useEffect } from 'react';
import { Button, Alert, Card } from 'antd';
import { useNavigate, useLocation } from 'react-router-dom';
import './login.less';
import { getToken } from 'utils/auth';
import { useAuth } from 'context/AuthContext';
import { AUTH_BASE_URL } from 'utils/request';

const LoginPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { user, loading, refresh, isAdmin } = useAuth();
  const searchParams = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const [error, setError] = useState(searchParams.get('error') || '');
  const [pending, setPending] = useState(false);

  useEffect(() => {
    setError(searchParams.get('error') || '');
  }, [searchParams]);

  useEffect(() => {
    const token = getToken();
    if (!token) return;
    if (!user && !loading) {
      refresh();
    }
    if (user) {
      navigate(isAdmin ? '/ops' : '/dev', { replace: true });
    }
  }, [user, loading, refresh, navigate, isAdmin]);

  const handleLogin = () => {
    setPending(true);
    try {
      const redirect = `${window.location.origin}${window.location.pathname}#/dev/dashboard`;
      const loginUrl = `${AUTH_BASE_URL}/auth/gitlab/login?redirect=${encodeURIComponent(redirect)}`;
      window.location.href = loginUrl;
    } catch (err) {
      setError(err.message || '无法发起登录请求');
      setPending(false);
    }
  };

  return (
    <div className="login-page">
      {error && (
        <Alert
          type="error"
          message={error}
          showIcon
          closable
          className="login-alert"
          onClose={() => setError('')}
        />
      )}
      <Card className="login-card">
        <h1>欢迎使用 Go DevOps</h1>
        <p className="login-subtitle">使用您的 Git 账户登录以管理仓库和流水线。</p>
        <Button type="primary" block size="large" loading={pending} onClick={handleLogin}>
          {pending ? '跳转中…' : '使用 Git 登录'}
        </Button>
      </Card>
    </div>
  );
};

export default LoginPage;

// web/src/views/login/login.vue
<template>
  <div class="login-page">
    <div v-if="error" class="alert alert--error login-alert">
      <span>{{ error }}</span>
      <button class="button button--ghost" @click="clearError">关闭</button>
    </div>
    <div class="login-card">
      <h1>欢迎使用 Go DevOps</h1>
      <p class="login-subtitle">使用您的 Git 账户登录以管理仓库和流水线。</p>
      <button class="button login-button" :disabled="loginPending" @click="login">
        {{ loginPending ? '跳转中…' : '使用 Git 登录' }}
      </button>
    </div>
  </div>
</template>

<script>
import { getToken } from '@/utils/auth'

const API_PREFIX = '/api/v1'

export default {
  name: 'LoginView',
  data() {
    return {
      loginPending: false,
      error: ''
    }
  },
  watch: {
    '$route.query.error'(val) {
      this.error = val || ''
    }
  },
  created() {
    const token = getToken()
    if (token) {
      this.$router.replace('/dashboard')
      return
    }
    this.error = this.$route.query.error || ''
  },
  methods: {
    login() {
      this.loginPending = true
      try {
        const redirect = `${window.location.origin}${window.location.pathname}#/dashboard`
        window.location.href = `${API_PREFIX}/auth/gitlab/login?redirect=${encodeURIComponent(redirect)}`
      } catch (err) {
        this.error = err.message || '无法发起登录请求'
        this.loginPending = false
      }
    },
    clearError() {
      this.error = ''
      if (this.$route.query.error) {
        this.$router.replace({ path: '/login' })
      }
    }
  }
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem 1rem;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: #ffffff;
  border-radius: 18px;
  box-shadow: 0 20px 45px rgba(79, 70, 229, 0.15);
  padding: 2.5rem 2rem;
  text-align: center;
}

.login-card h1 {
  margin: 0;
  font-size: 1.75rem;
  font-weight: 600;
  color: #1f2933;
}

.login-subtitle {
  margin: 0.75rem 0 2rem;
  color: #6b7280;
  font-size: 0.95rem;
}

.login-button {
  width: 100%;
}

.login-alert {
  max-width: 420px;
  width: 100%;
  margin-bottom: 1.5rem;
}

@media (max-width: 480px) {
  .login-card {
    padding: 2rem 1.5rem;
  }
}
</style>
